### ISSUE TITLE
Registration: can't go past Choose your password

### ISSUE THREAD

**Issue by andreis** [lavab/web#521] opened 2015-04-27 16:48 UTC
Filing a bug report on behalf of someone.

Where: production 0.2.6
Browser: Chrome Version 37.0.2062.122
Plugins: literally none except for https://chrome.google.com/webstore/detail/betafish-adblocker/gighmmpiobklfepjocnamgkkbiglidom

```
20Consider using 'dppx' units, as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) 
Initialize loader... VM51:6
loader: loading application utils undefined VM51:6
loader.progress 10 Loading Lavaboom utils(1)... VM51:6
loader loaded '/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js' Event VM51:6
loader.progress 20 Loading Lavaboom utils(2)... VM51:6
loader loaded '/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js' Event VM51:6
loader.progress 30 Checking... VM51:6
loader: initializing application utils undefined VM51:6
loader: calling rootScope.initializeApplication() VM51:6
checker: no token found! ctrlChecker.js:7
loader: loading application AppLavaboomLogin Object VM51:6
loader.progress 30 Loading openpgp.js... VM51:6
loader: initialized application utils with result undefined VM51:6
loader loaded '/vendor/openpgp.js' Event VM51:6
loader.progress 50 Loading templates... VM51:6
loader loaded '/js/templates-c1e1b066a5131b1bff135836b1793119f1e06b66.js' Event VM51:6
loader.progress 70 Loading Lavaboom... VM51:6
loader loaded '/js/appLavaboomLogin-9484387cfd14fbbe78d6c3b8566c49767902d7d5.js' Event VM51:6
loader.progress 90 Please wait... VM51:6
construct Cache instance name:  crypto cache options: Object cache.js:7
loader: initializing application AppLavaboomLogin Object VM51:6
loader: calling rootScope.initializeApplication() VM51:6
i18n index loaded Object translate.js:9
loader.progress 95 Initializing openpgp.js... VM51:6
Initialize openpgp in multi-threading mode, workers count:  4 crypto.js:159
opts Object ctrlLavaboomLogin.js:35
loader: initialized application AppLavaboomLogin with result Object VM51:6
loader.progress 100 Done! VM51:6
8TypeError: undefined is not a function
    at r.attr (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3208:20)
    at Object.T.(anonymous function) [as attr] (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3209:349)
    at Object.Yb.$set (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3113:325)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3110:112
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3130:326
    at Object.fn (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3162:31)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:356)
    at n.$apply (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:293)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3180:3
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74) angular.min.js:102
Calling tokens.create Array[1] ... LavaboomAPI.js:49
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.403' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.DEFAULT' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
tokens.create error:  Object LavaboomAPI.js:61
3Error: Wrong username or password.
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:2486
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Calling tokens.create Array[1] ... LavaboomAPI.js:49
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.403' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.DEFAULT' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
tokens.create error:  Object LavaboomAPI.js:61
3Error: Wrong username or password.
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:2486
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Calling tokens.create Array[1] ... LavaboomAPI.js:49
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.403' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.DEFAULT' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
tokens.create error:  Object LavaboomAPI.js:61
3Error: Wrong username or password.
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:2486
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Calling tokens.create Array[1] ... LavaboomAPI.js:49
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.403' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
Error: Translation 'LAVABOOM.API.ERROR.TOKENS.CREATE.DEFAULT' not found!
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:686
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
tokens.create error:  Object LavaboomAPI.js:61
3Error: Wrong username or password.
    at https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:277:2486
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:7647)
    at GeneratorFunctionPrototype.invoke (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:2:10228)
    at onFulfilled (https://mail.lavaboom.com/js/utils-7e4674cf2e188a838f8f11fe36df247bd074d8b8.js:74:19)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3153:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:106)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:102
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3085:155 angular.min.js:102
8TypeError: undefined is not a function
    at r.attr (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3208:20)
    at Object.T.(anonymous function) [as attr] (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3209:349)
    at Object.Yb.$set (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3113:325)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3110:112
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3130:326
    at Object.fn (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3162:31)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:356)
    at n.$apply (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:293)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3180:3
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74) angular.min.js:102
Calling accounts.create.verify Array[1] ... LavaboomAPI.js:49
accounts.create.verify:  Object LavaboomAPI.js:54
XMLHttpRequest cannot load https://technical.lavaboom.com/subscribe. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://mail.lavaboom.com' is therefore not allowed access. plan:1
Object angular.min.js:102
12TypeError: undefined is not a function
    at r.attr (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3208:20)
    at Object.T.(anonymous function) [as attr] (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3209:349)
    at Object.Yb.$set (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3113:325)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3110:112
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3130:326
    at Object.fn (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3162:31)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:356)
    at n.$apply (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:293)
    at HTMLButtonElement.<anonymous> (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3257:126)
    at HTMLButtonElement.c (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3073:389) angular.min.js:102
8TypeError: undefined is not a function
    at r.attr (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3208:20)
    at Object.T.(anonymous function) [as attr] (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3209:349)
    at Object.Yb.$set (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3113:325)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3110:112
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3130:326
    at Object.fn (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3162:31)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3164:356)
    at n.$apply (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3167:293)
    at https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3180:3
    at e (https://mail.lavaboom.com/js/utils-vendor-8447442756f09444cb9414b8ca40a1260ccb0794.js:3081:74) angular.min.js:102
```

**Comment by flixi** [comment] 2015-04-28 19:30
I just got the info that it works up until generating keys....It's broken though.

**Comment by let4be** [comment] 2015-05-04 09:33
I've just checked this and most likely this was caused by a:
https://github.com/lavab/web/issues/534
Can someone reproduce this after https://github.com/lavab/web/commit/0c9a2d6a09e886309d7aec1d83bbdf8276142cf9?

**Comment by let4be** [comment] 2015-05-04 09:35
Closing this, if it's still a problem, please reopen

**Comment by flixi** [comment] 2015-05-05 19:16
https://github.com/lavab/web/issues/558

**Comment by andreis** [comment] 2015-05-06 09:24
@vLooz reported this is still an issue for some users. We need to investigate this

**Comment by let4be** [comment] 2015-05-06 10:18
I'm finishing with client side part of logs tracking task, move to this right after this.

**Comment by let4be** [comment] 2015-05-06 14:45
@flixi master with bugfixes wasn't deployed...
.

**Comment by let4be** [comment] 2015-05-10 06:58
This should be fixed in current master long ago

**Closed by let4be** 2015-05-10 06:58 UTC
Labels: bug, important

**Comment by piggyslasher** [comment] 2015-05-10 07:46
if its on decrypting keys it might be webcrypto - took me almost 10 minutes last time when it was disabled.

**Comment by andreis** [comment] 2015-05-11 11:04
It's definitely that. Now, we could (1) warn our users that we don't support mobile or (2) simply work on responsive design. It depends on how much stuff to do/fix you have @piggyslasher. I'd rather just do the responsive design - it's going to be useful for ionic, too.
