### ISSUE TITLE
infinite scroll bug - show mail list as empty if you scroll up when loading next batch

### ISSUE THREAD

**Issue by piggyslasher** [lavab/web#508] opened 2015-04-22 08:23 UTC
not sure about you guys but I cant find of a dupe of this bug so I'm creating a new one. I know @let4be fixed something related recently. I wanted to report this earlier but I just couldnt replicate it. Now I think i found out where its going wrong.

When you scroll down and it starts loading new emails from your inbox, and during this instant you scroll back up you end up with a 

![image](https://cloud.githubusercontent.com/assets/1991125/7270036/94923960-e90b-11e4-813c-280913687823.png)

**Comment by mlooz** [comment] 2015-04-22 10:47
I encountered this bug before with Firefox on the Dev-branch, but couldn't reproduce it with Chrome or on .com, so I didn't report it yet. There is another instance of this: If you have more emails than fit on one page, scroll down and see the second page, you can get stuck on it and cannot go back to the first page, even if you scroll up again.

Steps to reproduce (sometimes):
1. Have more emails in the inbox than fit in one folder
2. Scroll down with Firefox
3.

**Comment by piggyslasher** [comment] 2015-04-22 10:58
1. Just before this happens - do you see a loading sign at the bottom of the threads list (middle panel)?
2. once this happens, try visiting the sent folder or simply another page and come back - can you scroll down? i cannot replicate this on my FF/mac.

**Comment by mlooz** [comment] 2015-04-22 11:46
Can't reproduce it right now, neither on .com or c62b90f3b4b60186b13afe458b8d56f3e0062a44
Firefox now shows a scroll bar, the bug only happened when no scroll bar was shown.

From memory:
1. I don't know
2. Visiting another page didn't help, I had to log out and log back in.

**Comment by piggyslasher** [comment] 2015-04-22 13:28
thanks alot. @let4be is probably the person who can fix this. i believe its part of the auto-loading as you scroll. because it just happened again. like I mentioned - when i scroll up as it is loading the next batch. the loading sign shows just before all my mails disappeared.

**Comment by let4be** [comment] 2015-05-04 15:03
I can't reproduce this behavior on the latest master, probably this was fixed long before.
Can someone confirm the bug still present on the latest master?

**Comment by mlooz** [comment] 2015-05-04 15:26
Cannot reproduce on 1e6ca6e8f21216df143bfce43304d89305c5eb7a, but on current .com.

**Comment by let4be** [comment] 2015-05-04 15:28
Ok let's see how it performs for few more days

**Comment by mlooz** [comment] 2015-05-04 20:55
Bad news: Bug occured just now on 03d1fbcb7b55f65f0c7d32d08de911428c6ca099.

The log contained some private information, a sanitized version can be found at https://gist.github.com/mlooz/c1edc9de038f9341836a

In only censored the email bodies, the thread view should be unaffected.
Issues #552 and #541 possibly related.

**Comment by let4be** [comment] 2015-05-05 10:20
Should be fixed, @mlooz could you please try to reproduce it again?

**Comment by mlooz** [comment] 2015-05-05 12:06
Reproduced just now with Firefox 37.02 on 1aa2c064e8bc60ddcba45e5c27e8176f1a71e4f0 (current master).
I'm afraid I can't give clear steps to reproduce, the bug appears only rarely.
I don't have time to sanitize the whole log again, let me now if I should look for something specific.

**Comment by let4be** [comment] 2015-05-05 12:07
Okay, will look into this more thoroughly - log doesn't really help here...

**Comment by piggyslasher** [comment] 2015-05-06 11:56
Its happening on my account (olga@lavaboom.com) all the time. You can replicate it by simply scrolling down the inbox. I can PM you my account details. Nothing private in there :)

**Comment by let4be** [comment] 2015-05-06 15:09
Okay, I reproduced one bug related with caching. Working on this

**Closed** 2015-05-06 16:17 UTC
Labels: bug, cannot reproduce, important, in progress
