### ISSUE TITLE
Request Key - no visible result

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#548] opened 2015-05-04 12:05 UTC
OS: Win 7
Browser: Firefox 37.0.2

1) Add new contact to address book
2) Click on open padlock
3) Click on "request key"

Nothing happens. Neither mail is sent out to this address, nor does anything else happen that might go for a request.

**Comment by let4be** [comment] 2015-05-04 15:08
Not implemented yet, duplicate of https://github.com/lavab/web/issues/548

**Closed by let4be** 2015-05-04 15:08 UTC
Labels: bug, important
