### ISSUE TITLE
Cannot delete old keys, and new keys don't decrypt immediately upon Import

### ISSUE THREAD

**Issue by satirist** [lavab/web#852] opened 2015-06-11 00:04 UTC
OS, browser: Mac OS 10.6.8, Chrome Version 44.0.2403.39 beta (64-bit)

Screenshots: Attached

Console logs: LMK if needed at specific steps etc.

* * * 

Walking through the screenshots...

01. We log in but have kept our private key local, so get alerted to that.
02. So, let's import our private key… 
03. Boom, done. Ah, now things get interesting:
	a. That loaded both our original key from 5/9 and our replacement key from 5/30.
	b. Both remain encrypted.
	c. We can't delete the original key from 5/9 (Auugh, want to get it out of there!)
04. Hey, let's now try logging out and then back in again.
05. Well, how about that! The old key's still unusable, but the newer one decrypted.

So, (2) issues to solve here(?):

First, ability to decrypt locally-retained keys without having to "Fonzie-smack" things with the login / logout move.

Second, ability to delete old keys if they're corrupted.

![01](https://cloud.githubusercontent.com/assets/12837455/8100346/761cf5bc-0fbf-11e5-9140-cdcc0ebadf7e.png)
![04](https://cloud.githubusercontent.com/assets/12837455/8100347/762dd4cc-0fbf-11e5-9bdf-4e4eb74960ae.png)
![02](https://cloud.githubusercontent.com/assets/12837455/8100348/762f8092-0fbf-11e5-89d5-e230b1495ed6.png)
![03](https://cloud.githubusercontent.com/assets/12837455/8100349/7644e25c-0fbf-11e5-9d58-8784c5568291.png)
![05](https://cloud.githubusercontent.com/assets/12837455/8100350/7646cb6c-0fbf-11e5-8caa-761cc18eabf2.png)

**Comment by JPL1** [comment] 2015-06-11 07:23
I have this issue too. Am waiting for my account to be reset.

**Comment by paulhugel** [comment] 2015-06-11 23:27
If lavaboom Sync is off and you log-out
what happens if you clear the Chrome browsing data  for one hour ?
Quit Chrome and relaunch Lavaboom are the keys gone ?
![screen shot 2015-06-11 at 1 26 00 pm](https://cloud.githubusercontent.com/assets/6466830/8120664/8374c3b0-103d-11e5-9d5a-dcebb4595564.png)

**Comment by satirist** [comment] 2015-06-12 01:16
Yes, I normally clear everything there when I quit Chrome and it doesn't make any difference to the problems I'm seeing. So when I either quit Chrome or manually clear browsing data, the private keys disappear as expected and then I have to re-Import if I want to use Lavaboom again. So that's great.

![screen shot 2015-06-11 at 6 08 38 pm](https://cloud.githubusercontent.com/assets/12837455/8121752/1dc62f40-1065-11e5-92ad-0e7734b0a3de.png)

So the issues are

a. When I Import my private key (.json file), both the 5/9 and 5/30 key appear, encrypted.
b. I can't delete the 5/9 key which as I understand is corrupted per issues Lavaboom had that day.
c. To get the (imported, valid) 5/30 key to decrypt, I have to log out of Lavaboom, then back in again.

**Comment by JPL1** [comment] 2015-06-12 10:22
>a. When I Import my private key (.json file), both the 5/9 and 5/30 key appear, encrypted.
>b. I can't delete the 5/9 key which as I understand is corrupted per issues Lavaboom had that day.
>c. To get the (imported, valid) 5/30 key to decrypt, I must next log out of Lavaboom, then back in again.

I have exactly the same problem, except even if I log out and back in again, and even if I use another browser and/or another PC I cannot decrypt the keys. Still waiting for someone at Lavaboom to reset my account .....

**Comment by let4be** [comment] 2015-06-15 07:50
@satirist this is intended behavior of not auto-decrypting imported private keys. Lavaboom does NOT know the password private key is encrypted with once you are inside your account(security measure).

you can easily decrypt any given private key manually without logout/login
just enter your passphrase here

![image](https://cloud.githubusercontent.com/assets/4147061/8155351/1651fa70-134c-11e5-9645-45a5973b41b8.png)

"Enter your passphrase" at the bottom

P.S. this is going to be re-designed soon to make it simpler ;)

**Comment by let4be** [comment] 2015-06-15 07:51
So I'm closing this, keys delete functionality coming soon along with security/keys redesign.
Keep and eye for updates ;)

**Closed by let4be** 2015-06-15 07:51 UTC

**Comment by satirist** [comment] 2015-06-15 15:19
Ah, OK cool. 

Thanks, and will do.
