### ISSUE TITLE
Key details for own key pair and contact keys show different information

### ISSUE THREAD

**Issue by mlooz** [lavab/web#492] opened 2015-04-16 11:53 UTC
For foreign keys, the key ID, length and algorithms is shown. For user keys, fingerprint, algorithms and creation date is shown.

Is this on purpose?
At least the fingerprint would be interesting for foreign keys as well.

**Comment by flixi** [comment] 2015-04-28 19:34
@vLooz

**Comment by vLooz** [comment] 2015-04-29 08:57
In my design it's the same.

Is there a technical reason, why it's different in the client @piggyshlasher?

**Comment by vLooz** [comment] 2015-04-29 09:03
It's regarding these older issues: 
Settings/Keys: https://github.com/lavab/web/issues/326
Contact/Keys:

**Comment by piggyslasher** [comment] 2015-04-29 09:15
closeing as dupe of #326 - i've asked @let4be for some more info on that. i currently don't have this data to display.

**Closed by piggyslasher** 2015-04-29 09:15 UTC
Labels: low priority, question
