### ISSUE TITLE
Send Public Key - no visible result

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#540] opened 2015-05-04 10:20 UTC
OS: Win 7
Browser: Firefox 37.0.2

Settings > Keys > Send Public Key shows no result. Has the key been sent to Lavaboom's keyserver, has it been sent to a public keyserver, was it intended to be sent by mail to another address but failed?

**Comment by let4be** [comment] 2015-05-04 14:29
This is still not implemented feature,
@flixi should it simple open a compose screen with attached public key?

**Comment by let4be** [comment] 2015-05-04 15:08
Duplicate of https://github.com/lavab/web/issues/459

**Closed by let4be** 2015-05-04 15:08 UTC
Labels: bug, important
