### ISSUE TITLE
Edit mode in contacts

### ISSUE THREAD

**Issue by let4be** [lavab/web#452] opened 2015-04-13 09:38 UTC
~~I've just added it but it looks not nice~~

![image](https://cloud.githubusercontent.com/assets/4147061/7113198/0bf797e0-e1da-11e4-85ef-4a6cc4a3cc92.png)

edit by @piggyslasher
  - [x] move edit button to action bar
  - [x] show editing mode save / discard buttons only when in editing mode
  - [x] Business / personal email only shown when business emails exist
  - [x] Show name / screen name as uneditable text in non-edit mode

**Comment by flixi** [comment] 2015-04-13 21:00
@vLooz Please do something here.

**Comment by vLooz** [comment] 2015-04-14 07:23
I agree, this doesn't look at all like I've designed it @flixi 

@piggyslasher, please look at my styleguides again and stick to it! The styleguides are on github for almost a month now. See https://github.com/lavab/web/issues/325

I want a clear separation into A) Non-Edit mode and B) Edit mode. 

![453 2015-04-14_contact edit master](https://cloud.githubusercontent.com/assets/11177812/7132228/a7637ba6-e287-11e4-8da9-75375589948b.jpg)

**Comment by piggyslasher** [comment] 2015-04-15 00:59
actually @vLooz - the version i left before i went on my break had your edit / discard buttons exactly where you wanted them. in the top corner. there's a regression here. I have to check what exactly was changed.

**Comment by piggyslasher** [comment] 2015-04-15 10:50
also the #325 was marked as Lava 2.1 so I didn't proceed with it. I will add the edit mode button in now. should be a quick fix.

**Comment by vLooz** [comment] 2015-04-15 11:04
nice! Could you make sure that in non-edit mode the whole Business mail section only is visible when there actually is a business mail added? @piggyslasher

**Comment by piggyslasher** [comment] 2015-04-15 11:37
![2015-03-17_contact_retouch add edit features-02](https://cloud.githubusercontent.com/assets/11177812/6759296/3d1ac188-cf3f-11e4-95e5-b5961bf9870b.png)
![2015-03-17_contact_retouch add edit features-03](https://cloud.githubusercontent.com/assets/11177812/6759297/3f512942-cf3f-11e4-95bf-b7d1077eeb35.png)
![2015-03-17_contact_retouch add edit features-04](https://cloud.githubusercontent.com/assets/11177812/6759299/40ffb8e4-cf3f-11e4-81e9-d9cecab0d38b.png)

  [ ] Business / personal email only shown when business emails exist
  [ ] Show name / screen name as uneditable text in non-edit mode

**Comment by vLooz** [comment] 2015-04-15 13:58
exactly :-)

**Comment by flixi** [comment] 2015-04-15 14:51
Can we close the issue?

**Comment by piggyslasher** [comment] 2015-04-15 15:13
@flixi - there's more to this issue because of the placement of the edit button and the edit/non-edit mode. maybe by tomorrow i can fix this completely.

**Comment by piggyslasher** [comment] 2015-04-17 09:58
fixed - edit mode now works. please check on develop. fixed on c491841a2df431c47a08f87c1354fe736089a68e

**Comment by piggyslasher** [comment] 2015-04-17 09:59
going to close this and continue styling on #325. so please comment there if you have any more request. or if its a new bug, create a new issue. thanks.

**Closed by piggyslasher** 2015-04-17 09:59 UTC
Labels: enhancement, important, styling required
