### ISSUE TITLE
Attachments not saved

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#542] opened 2015-05-04 10:24 UTC
OS: Win 7
Browser: Firefox 37.0.2

I tried sending myself a message with a public key attached. The GUI allowed me to click on the attachment, and displayed a bar graph informing me about the progress, but afterwards no downloaded attachment could be found on the local machine.

**Comment by let4be** [comment] 2015-05-04 11:04
duplicate of https://github.com/lavab/web/issues/517

**Closed by let4be** 2015-05-04 11:04 UTC
Labels: bug
