### ISSUE TITLE
Subject line sometimes not properly encoded

### ISSUE THREAD

**Issue by jrselzer** [lavab/web#767] opened 2015-05-22 05:06 UTC
Sorry, I have not found a way to reproduce this behaviour. Hope you have a chance to examine it anyway.

Sometimes even mails I wrote and sent with Lavaboom have broken subject lines like

=?utf-8?Q?Cryptoparty-Ank=C3=BCndigungstext?=

It actually should read "Cryptoparty-Ankündigungstext" (with a German u umlaut).

**Comment by pzduniak** [comment] 2015-05-22 05:12
Here we go again, @let4be you implemented client-side encoding, right?
22 maj 2015 07:06 "jrselzer" <notifications@github.com> napisał(a):

**Comment by let4be** [comment] 2015-05-22 08:08
not yet, still in todo

**Comment by pzduniak** [comment] 2015-05-22 15:24
Is this a Lavaboom to Lavaboom email?

**Comment by pzduniak** [comment] 2015-05-24 19:28
Ah yes, I finally understand it. lavab/web needs to support decoding of the subject lines.

**Comment by let4be** [comment] 2015-05-25 11:22
Duplicate of https://github.com/lavab/web/issues/746

**Closed by let4be** 2015-05-25 11:22 UTC
Labels: bug, important

**Comment by jrselzer** [comment] 2015-05-26 05:56
It only seems to affect Lavaboom mails going to external addresses, but I'll keep testing.
