### ISSUE TITLE
Compose: background makes lock icons invisible

### ISSUE THREAD

**Issue by let4be** [lavab/web#428] opened 2015-04-09 07:13 UTC
![image](https://cloud.githubusercontent.com/assets/4147061/7061968/08d5aaac-dea1-11e4-92fa-d6a37f37fa00.png)

**Comment by piggyslasher** [comment] 2015-04-21 09:25
closing this as its a dupe of #447 - there is a dropdown styling there I will follow.

**Closed by piggyslasher** 2015-04-21 09:25 UTC
Labels: bug, important
