### ISSUE TITLE
Encrypted emails in 'Sent' folder are not being diplayed

### ISSUE THREAD

**Issue by d3adb33f** [lavab/web#676] opened 2015-05-14 15:14 UTC
Encrypted emails are not being displayed in the 'Sent' folder, plain emails however are being displayed correctly.

![sent](https://cloud.githubusercontent.com/assets/7944405/7634556/fee492e8-fa5b-11e4-8e8d-71a7dea8bf48.png)
![sent1](https://cloud.githubusercontent.com/assets/7944405/7634573/26ba63b0-fa5c-11e4-9ecc-fec48a7ef096.png)

**Comment by let4be** [comment] 2015-05-14 15:15
Duplicate of https://github.com/lavab/web/issues/556
caused by https://github.com/lavab/api/issues/130

**Closed by let4be** 2015-05-14 15:15 UTC
