### ISSUE TITLE
Forward button doesn't work

### ISSUE THREAD

**Issue by flixi** [lavab/web#312] opened 2015-03-19 13:09 UTC
I can't forward anything to another email address.

**Comment by let4be** [comment] 2015-03-20 08:43
I'm not sure I correctly understand the expected behavior of forward button,
should it just forward the whole thread to the list of emails specified in the `to` field(and `cc`, `bcc`)?

**Comment by flixi** [comment] 2015-03-20 11:07
Yes, and eithr encrypting them with a new public key or decrypting them.

**Comment by let4be** [comment] 2015-03-21 08:53
@pzduniak I guess this need some API support, because else it's going 2 be a bunch of consequent API calls to emails.create

**Comment by let4be** [comment] 2015-03-30 15:59
Okay, regarding today's disussion going to implement this using the single API call and concatenating all emails clientside
But first - more important stuff

**Comment by let4be** [comment] 2015-04-02 13:53
Basic version is implemented, though styling required

**Comment by let4be** [comment] 2015-04-02 13:54
I've added simple email forwarding functionality, example how it currently looks:
![image](https://cloud.githubusercontent.com/assets/4147061/6965230/97cbeddc-d958-11e4-8f7c-0cfc5b84c490.png)

Template:
https://github.com/lavab/web/blob/develop/src/blocks/inbox/forwardedEmail.jade

**Comment by flixi** [comment] 2015-04-06 18:53
@vLooz Do you have any input?

**Comment by vLooz** [comment] 2015-04-07 09:57
I'm on it @flixi @let4be @piggyslasher

**Comment by vLooz** [comment] 2015-04-08 12:23
I'd suggest, that we use the same layout like "repeat mail" @piggyslasher

**Comment by flixi** [comment] 2015-04-13 20:52
It does work now, as far as I can tell.

**Comment by flixi** [comment] 2015-04-13 20:52
@vLooz @piggyslasher @let4be ?

**Comment by vLooz** [comment] 2015-04-14 07:53
I doesn't look nice, but it works. Definitely needs restyling. But right now there are other more important issues I guess.

**Comment by piggyslasher** [comment] 2015-04-15 04:13
let me have another look at this. last time it was blocked because forward was bugged.

**Comment by piggyslasher** [comment] 2015-04-21 15:57
![image](https://cloud.githubusercontent.com/assets/1991125/7256471/f94a0156-e881-11e4-887b-23fe3ec86b3b.png)

on develop. closing this for now. please re-open if you think it needs more work.

**Closed by piggyslasher** 2015-04-21 15:57 UTC
Labels: enhancement, important, in progress
