### ISSUE TITLE
Toggle Button guidelines

### ISSUE THREAD

**Issue by vLooz** [lavab/web#253] opened 2015-03-11 11:34 UTC
![2015-03-11_sliderbutton2](https://cloud.githubusercontent.com/assets/11177812/6595493/218779b2-c7eb-11e4-9a9f-6a53bdc7c5f1.png)

**Comment by let4be** [comment] 2015-03-11 11:36
mmm?

**Comment by vLooz** [comment] 2015-03-11 11:41
It's Version 2.0. I'm not totally happy with the slider buttons we have right now. When you guys have time I'd love to have them updated regarding this guidelines.

**Comment by piggyslasher** [comment] 2015-03-13 06:23
okay. let me have another go as this. i really didn't want to use any external plugins and kept it as minimal styling to a basic checkbox. let me try and get it more perfect.

**Comment by joergG** [comment] 2015-07-07 12:59
@piggyslasher - what's the status here?

**Comment by vLooz** [comment] 2015-07-14 12:23
Slight update on the toggle button.
We don't need to cover up any shadow anymore. Its just a colored oblong hole with a white circle on top of it, casting a shadow to the bottom right. This time with exact pixel measurements: 
![2015-07-14_sliderbutton3](https://cloud.githubusercontent.com/assets/11177812/8673021/a0a0034a-2a33-11e5-9d5e-b065ba172cce.png)

**Comment by joergG** [comment] 2015-07-21 12:44
@piggyslasher - rule it that you will push an issue to "Testing" when you dev-tested it and pushed it to Staging, so we can test it and assign me or @vLooz . We will then push it forward to "To ship" ourselves.
So is this on Staging already?

**Comment by vLooz** [comment] 2015-07-22 10:28
Looks great! Can be shipped from my pov!

**Comment by joergG** [comment] 2015-07-23 10:07
@vLooz - so we cannot close this until @piggyslasher answered your question?
-> should then leave it in "Testing"

**Comment by piggyslasher** [comment] 2015-07-23 10:37
Develop - the branch that I push my changes to when I've tested them
Staging - http://mail.lavaboom.io - @let4be will update this from Develop
branch. It is not something we can push to.

Like I said before. Unless you setup a local copy, you won't be able to see
my changes that I have already pushed to the develop branch. Only @let4be
can do this. Pushing to Develop is what I do. Staging is a web domain where
you can see the Develop branch when @let4be updates the server. I can only
move this to 'testing' once I've tested and it is in the main development
branch, but you won't be able to see it if @let4be hasn't updated .io. I
think the best way is to setup a local copy rather than wait for @let4be to
update staging.

And yes, it is in staging already. And @vLooz has seen it.

On Thu, 23 Jul 2015 at 18:07 joergG <notifications@github.com> wrote:

> @vLooz <https://github.com/vLooz> - so we cannot close this until
> @piggyslasher <https://github.com/piggyslasher> answered your question?
> -> should then leave it in "Testing"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lavab/web/issues/253#issuecomment-124041368>.
>
-- 
Vik Ramanujam
vik@ramanuj.am (official)
piggyslasher@gmail.com (everything else)
+6016 656 4647

**Comment by joergG** [comment] 2015-07-23 13:34
@piggyslasher - I don't know what this fuzz is all about.
1) I know that let4be "deploys" changes to staging environment
2) @vLooz asked you a question: "you're sure it's only 0.25 opactity?" which you didn't reply to and I simply asked him if the issue is solved or not.
3) @vLooz assigned @let4be which I also don't understand since this thing was deployed to staging already

guys, can it be so hard? is the shadow ok like this or does it have to be changed??

**Comment by vLooz** [comment] 2015-07-23 13:41
sorry for my part of the confusion @joergG 
I won't assign people or move cards anymore. 

The shadow is a low-prio thing, I'm happy to ignore if @piggyslasher has more important tasks to do right now. In case he is free, I of course would like him to double check the opacity.

**Comment by joergG** [comment] 2015-07-23 14:18
@vlooz - no worries, just didn't understand.
@piggyslasher - please just quickcheck the opacity.

**Comment by piggyslasher** [comment] 2015-07-24 06:36
Sorry. Mis-understood.

**Comment by piggyslasher** [comment] 2015-07-24 06:38
It is 25% opacity, but the spread was too much. It only needs to be about 7px to get exactly what you want. not 22.

**Comment by piggyslasher** [comment] 2015-07-24 06:39
Fixed.

**Comment by vLooz** [comment] 2015-07-24 08:28
Great! :)

**Closed** 2015-07-24 10:46 UTC
Labels: enhancement, info/help required, low priority
