### ISSUE TITLE
Getting rid of the ugly Angular links

### ISSUE THREAD

**Issue by andreis** [lavab/web#292] opened 2015-03-15 12:14 UTC
http://stackoverflow.com/questions/14771091/removing-the-hashtag-from-angularjs-urls-symbol
http://stackoverflow.com/questions/17893292/how-can-i-get-rid-of-the-hash-tag-in-my-angularjs-site-url

**Comment by pzduniak** [comment] 2015-03-15 12:14
Duplicate of #289

**Closed by pzduniak** 2015-03-15 12:14 UTC
