### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by creqke** [lavab/web#702] opened 2015-05-16 09:31 UTC
I got this issue after the Authenticating step when you register your account. 
![capture d ecran 2015-05-16 11 29 01](https://cloud.githubusercontent.com/assets/12471129/7665580/c4f1072e-fbbe-11e4-81c7-f44a5b413a74.png)

Here are the logs:

accounts.get error:  Object
Error: Invalid authorization token
    at https://mail.lavaboom.com/js/utils-4ee198d0bcb24e32faeb71e824e227aba32b014b.js:6733:1515
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2701:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2874:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as throw] (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2910:19)
    at onRejected (https://mail.lavaboom.com/js/utils-4ee198d0bcb24e32faeb71e824e227aba32b014b.js:2042:24)
    at https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6590:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6601:106)
    at https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:102
    at e (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6518:74)
checker: accounts.get(me) error Error: Invalid authorization token

Error: No such account
    at https://mail.lavaboom.com/js/utils-4ee198d0bcb24e32faeb71e824e227aba32b014b.js:6733:1515
    at tryCatch (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2701:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2874:22)
    at GeneratorFunctionPrototype.Gp.(anonymous function) [as throw] (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:2910:19)
    at onRejected (https://mail.lavaboom.com/js/utils-4ee198d0bcb24e32faeb71e824e227aba32b014b.js:2042:24)
    at https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6590:113
    at n.$eval (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:15)
    at n.$digest (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6601:106)
    at https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6604:102
    at e (https://mail.lavaboom.com/js/utils-vendor-6d747fe03913b25a37542b9a6cd249f62bfe7203.js:6518:74)
Object
loader: initialization of application failed AppLavaboom with error Error: No such account

**Comment by let4be** [comment] 2015-05-18 08:15
Issue is known and requires rework of signup process, caused by connection interruption during signup
I'm closing this for now and reopening in: https://github.com/lavab/web/issues/714
keep an eye on this

**Closed by let4be** 2015-05-18 08:15 UTC
