### ISSUE TITLE
Contacts: Some last improvements, then it's ready to go for MVP

### ISSUE THREAD

**Issue by vLooz** [lavab/web#442] opened 2015-04-09 16:27 UTC
The current state is much better then the last one, thx to @let4be & @piggyslasher 

To make it nice and usable for MVP, there are some last bugs to fix and one usability flaw to get rid of.

BUGS
See: https://files.slack.com/files-pri/T0393U6R6-F04AR8L1N/contact_bugs_hdready.mov

1) When I want to create a new business email it adds a new private email instead
Proposal: For MVP we do not differentiate email address types. What do you think @flixi @andreis ?

2) I typed a new email address in the field. Once I hit Enter, the field disappears and I have to start over.
Proposal: To hit Enter when you want to enter an information into the system, is common sense/best practice. This should save the information.

3) When I add a lavaboom address, the key is auto-synced (very nice) but after that it's shown in a very weird overlay way, instead of being collapsed. Please change.

4) When I saved the new Contact "Julia Zimmermann", it is still sorted under "+" in the Contact list.

USABILITY FLAWS

1) When adding a new email address, the cursor is not automatically inside the email field. You have to click into it until it accepts input. 
Proposal: once a email field is added, the cursor is in the field and you are ready to go.

2) Once all the contact information are set, I'd like to have the feature to "Save everything" and to leave edit mode. The buttons are in place already. The problem is they don't change to a non-edit mode. 
Proposal: Please implement a non-edit mode: no red circled minus buttons, no "add email" buttons, and instead of the X and the Tick in the header, there is just one "edit" button.

3) Once I click another Contact in the Contact list and click back on the contact I just edited, a blue bar appears that the contact is saved now. 
Proposal: I don't think we need this bar at all, once the user can see, that the edit mode is left after clicking the Tick.

**Comment by let4be** [comment] 2015-04-10 06:48
Are you sure this appears in the latest develop branch?
I fixed some of this in https://github.com/lavab/web/commit/86fe4157dabb3ecbc47dfcb42de39482a6826b90

P.S. we should have full support of private/business emails, both possible to add/remove and they display differently in compose typeahead

**Comment by let4be** [comment] 2015-04-10 07:02
> https://files.slack.com/files-pri/T0393U6R6-F04AR8L1N/contact_bugs_hdready.mov
isn't available

**Comment by andreis** [comment] 2015-04-10 12:32
Yeah I reported these too. A good way to report stuff to Sergey, if he's online, is to just Skype him + share the screen. :stuck_out_tongue: Done in 5 minutes.

**Comment by let4be** [comment] 2015-04-13 07:33
I've just checked the bug with (3) and it looks really weird - I cannot reproduce it locally, probably it's browser-specific
when key is being synced it somehow appears in the "opened" state without actually being opened
so collapse directive doesn't display correctly in the close state...

**Comment by let4be** [comment] 2015-04-13 08:03
@piggyslasher, @andreis do you have a problem with contact's key is being displayed weirdly in collapsed state?

**Comment by let4be** [comment] 2015-04-13 08:08
All of this should be fixed, the only problem is key collapsed/opened state as I cannot reproduce the issue

**Closed** 2015-04-13 11:43 UTC
Labels: bug, cannot reproduce, important
