### ISSUE TITLE
Settings/General: Annoying movement of forms due to blue info header

### ISSUE THREAD

**Issue by vLooz** [lavab/web#608] opened 2015-05-08 15:46 UTC
What happened:
Every time, when I do change something, the whole form would be pushed down by the blue info header. Very annoying. 

What should happen:
The Info header is nice, but it should go above the form without moving it. The form should stay in place.

**Comment by let4be** [comment] 2015-05-08 15:47
Duplicate of https://github.com/lavab/web/issues/582

**Closed by let4be** 2015-05-08 15:47 UTC
Labels: enhancement, low priority
