### ISSUE TITLE
Settings: key pair display design mocks

### ISSUE THREAD

**Issue by vLooz** [lavab/web#326] opened 2015-03-20 19:30 UTC
Andrei asked me to improve the way, key pairs are displayed. 
Please ask when you need more info about dimensions etc.

![2015-03-18_settings_keys_dialogs](https://cloud.githubusercontent.com/assets/11177812/6759371/d95f0388-cf3f-11e4-98f4-cfcd6e87b0f4.png)

**Comment by piggyslasher** [comment] 2015-03-21 07:15
@let4be how do we proceed with this?

**Comment by piggyslasher** [comment] 2015-04-07 14:52
@vLooz can we unify the styling for these two instances?

![image](https://cloud.githubusercontent.com/assets/1991125/7025792/7be81360-dd78-11e4-9013-a99e503f63aa.png)

and this, which is what i just finished in contacts.

![image](https://cloud.githubusercontent.com/assets/1991125/7025835/b7021a90-dd78-11e4-9195-17ee76d790c7.png)

**Comment by vLooz** [comment] 2015-04-07 15:19
I'd rather not unify them, because they show 2 different states. 
For MVP you could just ignore the third state though, because we probably won't have too many users, which want to add and delete key pairs during the first weeks.

**Comment by piggyslasher** [comment] 2015-04-07 15:28
sure. not a biggie. i just wanted to know if the new contacts collapse/expanded view is the latest. but they can be different. i just need to style the header.

**Comment by vLooz** [comment] 2015-04-07 15:29
nice! 
The new contacts UI definitely is the latest.

**Comment by piggyslasher** [comment] 2015-04-09 19:07
done mot of the logic and styling - check on develop. should be ready tomorrow. @let4be need to talk to you about the 'send public key' button. is there a function i can map to?

**Comment by piggyslasher** [comment] 2015-04-09 19:21
progress update:
![image](https://cloud.githubusercontent.com/assets/1991125/7074890/7c55e034-df30-11e4-8a54-42df0e1aadda.png)

@vLooz - how about the manage keys part - we have export & import.

**Comment by piggyslasher** [comment] 2015-04-09 19:22
@let4be maybe we just show the username or just the email address?
![image](https://cloud.githubusercontent.com/assets/1991125/7074930/c73303de-df30-11e4-8925-28f29fa3a476.png)

**Comment by vLooz** [comment] 2015-04-10 08:32
See here :-) 
![2015-03-18_settings_keys_dialogs](https://cloud.githubusercontent.com/assets/11177812/7084376/db8668e4-df6c-11e4-99a2-d0e56a194536.png)

**Comment by flixi** [comment] 2015-04-11 10:32
Please do not implement the stuff for pro-users quite yet.

**Comment by let4be** [comment] 2015-04-14 08:03
I'm at least going to show encrypted/decrypted status of the key - if not for production then it's for sure useful in development, same for manual key decryption

**Comment by piggyslasher** [comment] 2015-04-15 04:12
so we don't give the ability of adding a new key for non-pro users? @flixi @let4be @vLooz ?

right now that funcionality is in the the 4 buttons, which @vLooz didn't have in his mockups in the first place

![image](https://cloud.githubusercontent.com/assets/1991125/7152159/9ad7e62e-e368-11e4-888f-b75131d8a5e0.png)

**Comment by flixi** [comment] 2015-04-15 15:03
Nope, there is no way to currently add an own keypair.

**Comment by vLooz** [comment] 2015-04-15 15:34
Do we have the function "Generate new key pair" already? @pzduniak @flixi

**Comment by vLooz** [comment] 2015-04-15 15:51
I propose this: 
![2015-03-18_settings_keys_dialogs-08](https://cloud.githubusercontent.com/assets/11177812/7163022/0060e408-e398-11e4-8176-050c553788ad.png)

**Comment by pzduniak** [comment] 2015-04-15 16:02
I'm not sure if the minus and plus icons will mesh well with rest of the design, but I'm not an UI designer :smile: API was designed with a possibility of using multiple keypairs, so it will work. We also need some way to set one keypair as default, @vLooz.

**Comment by vLooz** [comment] 2015-04-15 16:25
Isn't the newest KeyPair the default automatically @pzduniak?

**Comment by piggyslasher** [comment] 2015-04-16 04:27
the plus/minus icons are really slick to be honest. they work nicely. i'll change the add button to generate new key pair. that leaves

  - [] import keys
  - [] export keys
  - [] and the still ambiguous _remove decrypted keys_

**Comment by vLooz** [comment] 2015-04-16 08:44
Didn't @flixi say, that "importing keys" is not possible right now?

The "remove key" option definitely is a Pro user feature! 
Maybe "generate new keypair" should be as well, I'm worried that a unskilled user could mess with the system even by just generating a new keypair. Is that worry valid? What do you think @andreis @flixi?

**Comment by flixi** [comment] 2015-04-16 10:57
Yes, that worry is valid. So, please remove those features.
But keep the decrypt functionality thoug @piggyslasher

**Comment by vLooz** [comment] 2015-04-16 16:09
Alright. So basically the (-) and (+) Icons and the connected function only appear in Edit Mode for Pro User - which we don't offer in MVP.

**Comment by piggyslasher** [comment] 2015-04-21 14:07
wait. importing keys is necessary if you are on a new browser and you have your key on your thumbdrive or something. that was the whole rationale behind it. i had to use it a couple of times before i starting using lavaboom sync - otherwise i couldnt decrypt emails or anything after logging in.

**Comment by vLooz** [comment] 2015-04-21 14:45
This is only a problem, when the user switches off Lavaboom-Sync @piggyslasher 

Although we should add an info text  - or even a popUp - to the toggle switch, informing the user that she needs to switch on "Expert Mode" to manage & uploads the keys.

Or we can hide the Lavaboom-Sync-Switch in Expert-Mode entirely.

**Comment by piggyslasher** [comment] 2015-04-21 14:57
no worries. i can hide the import button now. can re-enable here or somewhere else with different styling when necessary.

**Comment by piggyslasher** [comment] 2015-04-21 15:42
okay. import also removed. now only decrypt keys remains. please let me know how to proceed with this. marking as blocked and design-wanted.

**Comment by piggyslasher** [comment] 2015-04-21 16:05
assigning to @vLooz because I need to know a rough mockup of how you want the decrypting to work. thanks.

**Comment by vLooz** [comment] 2015-04-22 09:38
Could you write me a rough use case for the decrypting scenario, so I know in which situation which function needs a button? @andreis 
Thx

**Comment by andreis** [comment] 2015-04-22 10:25
Decrypting what, keys? Well, as we discussed it there are two cases when decrypting keys is necessary:

1. LSync on, but the user changed the passphrase of a key while in Expert Mode.
2. LSync off, keyring uploaded by the user, or found in browser cache. (The keyring always contains **encrypted** private keys)

In both cases every key pair needs a way to be decrypted individually.

Idea: we can make the user's life easier by trying to decrypt *all* the keys whenever he inputs a passphrase.

**Comment by vLooz** [comment] 2015-04-22 11:42
I understand scenario 2. When the keypair/keyring was encrypted with a different passphrase then the actual account passphrase, the user needs to decrypt it,

I don't fully understand scenario 1 though. Why would a user want to change the passphrase to a keypair?

**Comment by vLooz** [comment] 2015-04-22 16:13
Is this feasible @andreis? 

If yes, just re-use existing code from similar overlays/pop-up's @piggyslasher. If you'd prefer a styleguide anyway, let me know!

![2015-04-22_settings keys add keypairs](https://cloud.githubusercontent.com/assets/11177812/7279267/ec3081ea-e91a-11e4-9961-6ef4bd525420.png)

**Comment by flixi** [comment] 2015-04-23 07:31
Yes, I like your deisgns @vLooz. @piggyslasher Please implement a warning if there is no key detected upon login.

**Comment by andreis** [comment] 2015-04-23 08:50
I'm going to draw a big diagram with all the possibilities and give to @vLooz to make it pretty.

**Comment by vLooz** [comment] 2015-04-23 09:03
sounds good @andreis

**Comment by flixi** [comment] 2015-04-28 19:41
Status on that?

**Comment by andreis** [comment] 2015-04-28 20:18
Shit, I forgot. Sorry, I'll finish it tomorrow (it's on a sheet of paper on my desk).

**Comment by flixi** [comment] 2015-04-29 12:27
Grand, it lies there perfect!

**Closed** 2015-05-10 15:21 UTC
Labels: enhancement, important, styling required
