### ISSUE TITLE
Inbox: Please add line below first email (before selected)

### ISSUE THREAD

**Issue by vLooz** [lavab/web#386] opened 2015-04-01 16:30 UTC
![bildschirmfoto 2015-04-01 um 18 29 34](https://cloud.githubusercontent.com/assets/11177812/6945883/20ed2a70-d89d-11e4-979b-e80a96e332fb.png)

**Comment by piggyslasher** [comment] 2015-04-02 16:18
closing #395 because this is related and its the only remaining issue from there. but i can't do this if selected, remove the border because it means the border will be _inside_ if the item is not selected. i.e. 1px too high.

**Comment by vLooz** [comment] 2015-04-02 16:20
Humm..ok. What about autoselect the mail at the top when starting the client?

**Comment by piggyslasher** [comment] 2015-04-02 16:31
the problem is when the last item is active, the border is still visible.

there's two parts to this problem:
  - [x] show border on last item - fixed
  - [ ] hide border if last item is selected - can't be done using css alone, and we need dreaded javascript, which _should not_ be used for cosmetics

**Comment by piggyslasher** [comment] 2015-04-02 16:31
let me make a push. and you can tell me if things are fine.

**Comment by vLooz** [comment] 2015-04-02 17:03
To me it looks like, as if the the border, which should be at the bottom the field, actually is on the top.

![bildschirmfoto 2015-04-02 um 19 01 36](https://cloud.githubusercontent.com/assets/11177812/6968916/dbdde0a4-d96a-11e4-90dd-c0a930ea324d.png)
I'm sorry, I don't really understand the issue.

**Closed** 2015-04-02 18:01 UTC
Labels: enhancement, ready
